// This file is @generated by prost-build.
#[derive(sea_orm::EnumIter, sea_orm::DeriveActiveEnum)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CastleType {
    Undefined = 0,
    Heaven = 1,
    Inferno = 2,
    Necropolis = 3,
    Preserve = 4,
    Dungeon = 5,
    Academy = 6,
    Fortress = 7,
    Stronghold = 8,
}
impl CastleType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Undefined => "CASTLE_TYPE_UNDEFINED",
            Self::Heaven => "CASTLE_TYPE_HEAVEN",
            Self::Inferno => "CASTLE_TYPE_INFERNO",
            Self::Necropolis => "CASTLE_TYPE_NECROPOLIS",
            Self::Preserve => "CASTLE_TYPE_PRESERVE",
            Self::Dungeon => "CASTLE_TYPE_DUNGEON",
            Self::Academy => "CASTLE_TYPE_ACADEMY",
            Self::Fortress => "CASTLE_TYPE_FORTRESS",
            Self::Stronghold => "CASTLE_TYPE_STRONGHOLD",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CASTLE_TYPE_UNDEFINED" => Some(Self::Undefined),
            "CASTLE_TYPE_HEAVEN" => Some(Self::Heaven),
            "CASTLE_TYPE_INFERNO" => Some(Self::Inferno),
            "CASTLE_TYPE_NECROPOLIS" => Some(Self::Necropolis),
            "CASTLE_TYPE_PRESERVE" => Some(Self::Preserve),
            "CASTLE_TYPE_DUNGEON" => Some(Self::Dungeon),
            "CASTLE_TYPE_ACADEMY" => Some(Self::Academy),
            "CASTLE_TYPE_FORTRESS" => Some(Self::Fortress),
            "CASTLE_TYPE_STRONGHOLD" => Some(Self::Stronghold),
            _ => None,
        }
    }
}
